apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa
  labels:
    app: workflow-service
  name: workflow-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-service
  strategy: {}
  template:
    metadata:
      labels:
        app: workflow-service
    spec:
      containers:
        - image: 411194283529.dkr.ecr.us-east-1.amazonaws.com/workflow-service:1.0.0
          name: workflow-service
          ports:
            - containerPort: 8080
          resources: {}
          imagePullPolicy: Always
          env:
           - name: MYSQL_HOST
             value: nv-non-prod-mysql.navulia.cloud
           - name: MYSQL_USERNAME
             value: workflow_u
           - name: MYSQL_PASSWORD
             value: workflowU123$rtSS
           - name: SPRING_PROFILES_ACTIVE
             value: qa