apiVersion: v1
kind: Service
metadata:
  name: workflow-nodeport-service
  labels:
   app: workflow-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  selector:
    app: workflow-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort