package com.xitricon.workflowservice.model.enums;

public enum WorkFlowStatus {
	INITIATED, SUBMISSION_IN_PROGRESS, PENDING_REVIEW, REVIEW_INPROGRESS, PENDING_APPROVAL_STAGE1,
	APPROVAL_INPROGRESS_STAGE1, PENDING_APPROVAL_STAGE2, APPROVAL_INPROGRESS_STAGE2, APPROVED, CORRECTION_INPROGRESS,
	PENDING_CORRECTION, PENDING_REVIEWER_CORRECTIONS, REVIEWER_CORRECTIONS_IN_PROGRESS
}
