package com.xitricon.workflowservice.model.enums;

public enum WorkFlowStatus {
	INITIATED, SUBMISSION_IN_PROGRESS, PENDING_REVIEW, REVIEW_INPROGRESS, PENDING_APPROVAL, APPROVAL_INPROGRESS,
	APPROVED
}
